config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new'
  get 'tasks/:id', to: 'tasks#show', as: :task
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class="container">
  <div class="form-group"><%= form_for(@task) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :details %>
    <%= f.text_field :details %>
    <%= f.label :completed %>
    <%= f.text_field :completed %>
    <%= f.submit %>
  <% end %>
  </div>
</div>
<!-- <form>
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
  </div>
  <div class="form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Check me out</label>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form> -->

app/views/tasks/index.html.erb
<div class="container">
  <h1>My tasks</h1><br><br>
  <% @tasks.each do |task| %>
    <% if task.completed %>
      <input type="checkbox" checked>
      <label for="task"><%=link_to task.title, task_path(task) %></label><br><br>
    <% else %>
      <input type="checkbox">
      <label for="task"><%=link_to task.title, task_path(task) %></label><br><br>
    <% end %>
  <% end %>
  <%= link_to "➕ Create a new task", tasks_new_path %>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <%= form_for(@task) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :details %>
    <%= f.text_field :details %>
    <%= f.label :completed %>
    <%= f.text_field :completed %>
    <%= f.submit %>
  <% end %>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <div class="card">
    <h5 class="card-header">My tasks</h5>
    <div class="card-body">
      <h5 class="card-title"><%= @task.title %>
        <%= link_to "🗑", task_path(@task), method: :delete, data: { confirm: "Are you sure?" } %></h5>
      <p class="card-text"><%= @task.details %></p>
      <% if @task.completed %>
        <input type="checkbox" checked>
        <label for="task">Task is completed.</label>
      <% else %>
        <input type="checkbox"><label for="task">Task is not completed.</label><br>
      <% end %>
      <br><button class="btn btn-light"><%= link_to "Update", edit_task_path(@task) %></button><br>
    </div>
</div>
<br><%= link_to "Back to list", tasks_path %><br>